<!DOCTYPE html>

<head>
    <meta charset="utf-8">
    <title>Pirate Ipsum</title>
    <meta name="description" content="">
    <link rel="stylesheet" href="">

    <style type="text/css">
    * {
        color: white;
    }
        body {
            background-image: url("water-b.jpg");
            background-repeat: no-repeat, repeat;
            background-size: 1000px;
        }

        h1 {
            font-size: 2.5em;
        }

        p {
            font-size: 1.3em;
            width: 690px;
        }

        table {
            font-size: 1.3em;
            width: 690px;
            border: 1px solid lightblue;
        }

        ul {
            font-size: 1.1em;
            width: 690px;
        }
        a {
            color: aqua;
        }

        button {
            color: black;
        }
    </style>

</head>

<body>
    <h1>Pirates of the Caribbean</h1>
    <img src="piratedude.png" alt="Pirate guy" height="300px">
    <p>Aft ye hempen halter cog fire in the hole Gold Road strike colors galleon furl Sink me. Warp loot sutler pirate
        chandler boom hang the jib trysail Yellow Jack nipper. Yawl Nelsons folly me Corsair shrouds mizzenmast no prey,
        no pay bowsprit overhaul draught.</p>
    <p>Gold Road topmast fluke jolly boat salmagundi dead men tell no tales provost walk the plank spirits lateen sail.
        Tackle parley take a caulk to go on account ho Barbary Coast sutler prow fire in the hole bilge. Execution dock
        cog ye hogshead deadlights overhaul scuppers boatswain yardarm doubloon.</p><br>
    <table>
        <thead>
            <tr>
                <th>Rank</th>
                <th>Title</th>
                <th>Gross</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Dead Man's Chest</td>
                <td>$423,315,812</td>
                <td>7/7/06</td>
            </tr>
            <tr>
                <td>2</td>
                <td>At World's End</td>
                <td>$309,420,425</td>
                <td>5/25/07</td>
            </tr>
            <tr>
                <td>3</td>
                <td>The Curse of the Black Pearl</td>
                <td>$305,413,918</td>
                <td>7/9/03</td>
            </tr>
            <tr>
                 <td>4</td>
                 <td>On Stranger Tides</td>
                 <td>$241,071,802</td>
                 <td>5/20/11</td>
             </tr>
             <tr>
                <td>5</td>
                <td>Dead Men Tell No Tales</td>
                <td>$172,558,876s</td>
                <td>5/26/17</td>
            </tr>
        </tbody>
    </table>

    <ul>
        <p>Main Characters</p>
        <li>Jack Sparrow</li>
        <li>Hector Barbossa</li>
        <li>Joshamee Gibbs</li>
        <li>Will Turner</li>
        <li>Elizabeth Swann</li>
    </ul>
    <a href="https://www.youtube.com/watch?v=naQr0uTrH_s">Click for the The Curse of the Black Pearl trailer</a> 

    <h3>Please take this short survey</h3>
    <form>
        <label for='email'>Email: </label>
            <input type="email" name="email" id="email"><br>
        <label for='password'>Password: </label>
            <input type="password" name="password" id="password"><br>
            <input type="radio" name="survey" id="" value="yes">Yes, please send me lots of emails<br>
        <label for='checkbox'>How did you hear about us? </label><br>
            <input type="checkbox" name="facebook" value="facebook">facebook<br>
            <input type="checkbox" name="newspaper" value="newspaper">Newspaper<br>
            <input type="checkbox" name="referral" value="referral">Referral<br>
            <button type="submit" name="submit">Submit</button>
        </form>

</body>

</html>
