* {
  margin: 0px;
  padding: 0px;
  box-sizing: border-box;
}

body {
  background-image: linear-gradient(to bottom left, #4e3a43, #4e3a43);
}

a:link {
  color: black;
}

#header {
  display: inline-block;
  margin: 0px;
  padding: 20px;
  background-color: white;
  box-sizing: border-box;
  width: 100%;
}

#header h1,
h2 {
  display: inline-block;
  margin: 5px;
}

#header h2 {
  display: inline-block;
  float: right;
}

#main {
  display: inline-block;
  margin: 10px auto;
  width: 100%;
}

#main .about-photo {
  display: inline-block;
  margin: 10px;
  padding: 7px;
  background-color: #c0c0c0;
  width: 45%;
  /* border: #4e3a43; */
}

#main .about {
  display: inline-block;
  margin: 5px;
  background-color: #eee8ee;
  width: 45%;
  vertical-align: top;
}

#main .about-info {
  padding: 0px 10px 40px 10px;
}
#main .titles {
  margin: 0px;
  padding: 8px 10px;
  width: 100%;
  background-image: linear-gradient(#aeadb2, #878593, #aeadb2);
  color: white;
  display: block;
}

#container {
  display: inline-block;
  margin: 0px;
  width: 100%;
}

#container .titles {
  margin: 0px;
  padding: 8px 10px;
  width: 100%;
  background-image: linear-gradient(#aeadb2, #878593, #aeadb2);
  color: white;
  display: block;
}

#container .sub-titles {
  margin-top: 20px;
  padding: 5px;
  width: 100%;
  background-image: linear-gradient(#aeadb2, #878593, #aeadb2);
  color: white;
  display: block;
}

#container .block {
  display: inline-block;
  margin: 15px;
  padding: 0px;
  background-color: #eee8ee;
  width: 30%;
  vertical-align: top;
}

#container .info {
  margin: 15px;
  padding: 10px;
}

#container .mini-logos img {
  margin: 5px 10px 5px 10px;
  display: inline-block;
}

button {
  background-color: #407d61; /* Green */
  border: 0.7px solid black;
  color: white;
  padding: 10px 5px;
  text-align: center;
  display: inline-block;
  font-size: 12px;
  border-radius: 8px;
  box-shadow: 5px 2px #aca8ab;
  margin-bottom: 20px;
}

.center-button {
  text-align: center;
}

#footer {
  text-align: center;
  margin-top: 20px;
}
footer {
  min-height: 70px;
  background-color: white;
  margin: 0px;
}

#social-media {
  /* vertical-align: bottom; */
  margin-top: 10px;
}

#social-media .sm-photos {
  vertical-align: bottom;
  margin-top: 5px;
}
