<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Portfolio</title>
    <link rel="stylesheet" type="text/css" href="style.css" />
</head>

<body>
    <div id="header">
        <h1>Jayne Doe</h1>
        <h2>Master of shadows and the Internet!</h2>
    </div>
    <div id="main">
        <img src="Portfolio_images/photo_of_me.jpg" class="about-photo" alt="Lady with glasses" width=500px;>
        <div class="about">
            <h2 class="titles">About...</h2>
            <div class="about-info">
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quis mollitia nostrum
                    consequatur corrupti
                    perferendis laboriosam reprehenderit iure, vel quo cum</p><br>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Expedita nostrum necessitatibus blanditiis
                    dignissimos asperiores dolores commodi doloremque. Vero reprehenderit labore qui, nesciunt optio
                    fugit
                    dolores deserunt mollitia, provident nihil rem placeat maxime facilis velit, impedit asperiores
                    reiciendis.
                    Facere delectus perferendis dicta praesentium! Nesciunt temporibus beatae eius ducimus fugit
                    adipisci
                    odit
                </p><br>
                <a href="www.google.com" class="link">Continue reading...</a>
            </div>
        </div>
    </div>
    <div id="container">
        <div class="block">
            <h2 class="titles">La Mode</h2>
            <img src="Portfolio_images/lamode.png" alt="La mode" width=300px>
            <p class="info">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim voluptatibus totam
                accusantium vel,
                maiores
                praesentium soluta aut exercitationem, tempore, ea excepturi non vitae reprehenderit nihil.</p>
            <h4 class="sub-titles">Technologies:</h4>
            <div class="mini-logos">
                <img src="Portfolio_images/php.png" alt="php" width=40px>
                <img src="Portfolio_images/codeigniter.png" alt="php" width=40px>
                <img src="Portfolio_images/jQuery.png" alt="jquery" width=40px>
                <img src="Portfolio_images/ajax.png" alt="ajax" width=40px>
                <img src="Portfolio_images/codeigniter.png" alt="php" width=40px>
                <img src="Portfolio_images/mysql.png" alt="mysql" width=40px>
                <img src="Portfolio_images/HTML.png" alt="html" width=40px>
                <img src="Portfolio_images/CSS.png" alt="css" width=40px>
                <img src="Portfolio_images/bootstrap.png" alt="bootstrap" width=40px>
            </div>
            <div class="center-button">
                <button type="button">La Mode</button>
            </div>
        </div>
        <div class="block">
            <h2 class="titles">La Mode</h2>
            <img src="Portfolio_images/lamode.png" alt="La mode" width=300px>
            <p class="info">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim voluptatibus totam
                accusantium vel,
                maiores
                praesentium soluta aut exercitationem, tempore, ea excepturi non vitae reprehenderit nihil.</p>
            <h4 class="sub-titles">Technologies:</h4>
            <div class="mini-logos">
                <img src="Portfolio_images/php.png" alt="php" width=40px>
                <img src="Portfolio_images/codeigniter.png" alt="php" width=40px>
                <img src="Portfolio_images/jQuery.png" alt="jquery" width=40px>
                <img src="Portfolio_images/ajax.png" alt="ajax" width=40px>
                <img src="Portfolio_images/codeigniter.png" alt="php" width=40px>
                <img src="Portfolio_images/mysql.png" alt="mysql" width=40px>
                <img src="Portfolio_images/HTML.png" alt="html" width=40px>
                <img src="Portfolio_images/CSS.png" alt="css" width=40px>
                <img src="Portfolio_images/bootstrap.png" alt="bootstrap" width=40px>
                <div class="center-button">
                    <button type="button">La Mode</button>
                </div>
            </div>
        </div>
        <div class="block">
            <h2 class="titles">La Mode</h2>
            <img src="Portfolio_images/lamode.png" alt="La mode" width=300px>
            <p class="info">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim voluptatibus totam
                accusantium vel,
                maiores
                praesentium soluta aut exercitationem, tempore, ea excepturi non vitae reprehenderit nihil.</p>
            <h4 class="sub-titles">Technologies:</h4>
            <div class="mini-logos">
                <img src="Portfolio_images/php.png" alt="php" width=40px>
                <img src="Portfolio_images/codeigniter.png" alt="php" width=40px>
                <img src="Portfolio_images/jQuery.png" alt="jquery" width=40px>
                <img src="Portfolio_images/ajax.png" alt="ajax" width=40px>
                <img src="Portfolio_images/codeigniter.png" alt="php" width=40px>
                <img src="Portfolio_images/mysql.png" alt="mysql" width=40px>
                <img src="Portfolio_images/HTML.png" alt="html" width=40px>
                <img src="Portfolio_images/CSS.png" alt="css" width=40px>
                <img src="Portfolio_images/bootstrap.png" alt="bootstrap" width=40px>
            </div>
            <div class="center-button">
                <button type="button">La Mode</button>
            </div>
        </div>
    </div>
    <div id="footer">
        <footer>
            <p>jdoe@gmails.com | 206-555-1212</p>
            <div id="social-media">
                <img src="Portfolio_images/github.png" alt="github" width=20px class="sm-photos">
                <a href="www.google.com">jaynedev</a>
                <img src="Portfolio_images/linkedin.png" alt="linkedin" width=20px class="sm-photos">
                <a href="www.google.com">jayne-doe</a>
                <img src="Portfolio_images/twitter.png" alt="twitter" width=20px class="sm-photos">
                <a href="www.google.com">jdtweets</a>
                <img src="Portfolio_images/codepen.png" alt="codepen" width=20px class="sm-photos">
                <a href="www.google.com">jaynedev</a>
            </div>
        </footer>
    </div>
</body>
</html>
